### ISSUE TITLE
Server-side rendering

### ISSUE THREAD

**Issue by plouc** [StateOfJS/StateOfJS#10]
Think about server-side-rendering for text and graphs. Ideally, graphs should be converted to PNG for easy sharing.

This would be an argument for using Gatsby or Next, but I think that would require migrating away from React Router, so it's not a trivial move…

**Comment by plouc** [comment]
@SachaG I made a test, (see https://github.com/StateOfJS/StateOfJS/pull/26/files), I've some screenshots for most of the pages.

The way it works:
- add required pages to `cli/conf/base.yaml`, you'll see a `capture.pages` entry, it'as an array composed of urls and selectors, it will be used later to load the page and make a screenshot of the area matching the bounding box of the selected element
- `cd cli && ./cli capture`
- and that's it, generated images are saved in `static/images/captures`, using a sanitized version of the configured url

**Comment by SachaG** [comment]
Actually maybe we should store the images in `/public` and not `/static`? Since `/public` is the build directory.

**Comment by plouc** [comment]
but they won't be available during development then, am I right?

**Comment by SachaG** [comment]
Not available to Gatsby maybe, but it's not like we need to display them anyway?

**Comment by SachaG** [comment]
Not quite working yet: https://philatist-albert-72527.netlify.com/images/captures/front_end_results.png

I guess with the current setup we need to commit the images to the git repo?

**Comment by SachaG** [comment]
Also I get this error: 
```
✘  ~/Dev/stateOfJS/cli   nivo ●  ./cli capture
Starting capture for 26 page(s)
  baseUrl:   http://localhost:8000/2017
  outputDir: ../public/images/captures

Capturing /flavors/results/ (selector: .capture)

oops, something went wrong :(
Error: net::ERR_CONNECTION_REFUSED
    at navigate (/Users/sacha/Dev/StateOfJS/node_modules/puppeteer/lib/Page.js:488:37)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by plouc** [comment]
Did you started the dev server?

**Comment by SachaG** [comment]
Whoops :p

**Comment by plouc** [comment]
I should have added a check to ensure the server is started before starting the process.
