### ISSUE TITLE
Harmonize Heatmaps design

### ISSUE THREAD

**Issue by SachaG** [StateOfJS/StateOfJS#110]
![https://d3vv6lp55qjaqc.cloudfront.net/items/233v0x221L1M1u1i1x1Q/Screen%20Shot%202018-11-16%20at%2011.59.28.png?X-CloudApp-Visitor-Id=43642&v=fad1a4e1](https://d3vv6lp55qjaqc.cloudfront.net/items/233v0x221L1M1u1i1x1Q/Screen%20Shot%202018-11-16%20at%2011.59.28.png?X-CloudApp-Visitor-Id=43642&v=fad1a4e1)

![https://d3vv6lp55qjaqc.cloudfront.net/items/0B0F3o3n3g0n0g1C0z3l/Screen%20Shot%202018-11-16%20at%2011.59.22.png?X-CloudApp-Visitor-Id=43642&v=2df7a547](https://d3vv6lp55qjaqc.cloudfront.net/items/0B0F3o3n3g0n0g1C0z3l/Screen%20Shot%202018-11-16%20at%2011.59.22.png?X-CloudApp-Visitor-Id=43642&v=2df7a547)

**Comment by plouc** [comment]
I don't think we must use the same styles, those are really different

**Comment by SachaG** [comment]
I improved them a little anyway.

**Comment by plouc** [comment]
<img width="988" alt="screenshot 2018-11-16 at 17 35 18" src="https://user-images.githubusercontent.com/501642/48608596-0f0b5f00-e9c6-11e8-85f7-337ceadc0cdf.png">

**Comment by plouc** [comment]
I think we should add a bottom border to the last item too, it's different from the other tools heatmap where we have the latest line showing averages
