### ISSUE TITLE
Show absolute counts on overall chart

### ISSUE THREAD

**Issue by SachaG** [StateOfJS/StateOfJS#112]
> @sacha in other libraries, we can see the mention count, but for other charts it's only a percentage. We're losing some information here. Is it guaranteed that libraries listed in "other libraries" got less votes than the libraries in Overview ? Or might it be that, let's take data layer, VueX is actually more popular than Relay Modern ?

Maybe we can show it in the tooltip? Or else add a switcher like in 2016?

**Comment by plouc** [comment]
We now can switch between percents/counts, also implemented on **opinion over time**, **salary breakdown**, **years of experience breakdown** and **company size breakdown** charts.
See https://github.com/StateOfJS/StateOfJS/commit/fac3c945ca1cfedce450720b4fb83774d49290cd
