### ISSUE TITLE
Improve overall chart tooltips

### ISSUE THREAD

**Issue by SachaG** [StateOfJS/StateOfJS#113]
Sometimes, the tooltips aren't translated (`would_use` -> `would use again`).

- [x] Section overview chart
- [x] Tool opinion over time chart

**Comment by plouc** [comment]
Toop opinion over time fixed by https://github.com/StateOfJS/StateOfJS/commit/fac3c945ca1cfedce450720b4fb83774d49290cd

**Comment by plouc** [comment]
Section overview chart fixed by https://github.com/StateOfJS/StateOfJS/commit/9eddab29f969553c836cecee262116967d66be82

Please make sure to re-install dependencies.
