### ISSUE TITLE
Best of JS popup/tooltip

### ISSUE THREAD

**Issue by plouc** [StateOfJS/StateOfJS#12]
Use Best of JS API to show related library info in tooltip or popover.

@michaelrambeau do you have some kind of API spec (such as swagger) to ease integration?

**Comment by SachaG** [comment]
Data to display:

- Library name
- Description
- Link to best of JS page
- Link to homepage
- Link to GitHub
- Number of stars

We could either set up an API of some kind (i.e. `http://bestof.js.org/api/?project=react`), or else just generate a static JSON with all the data. I think that second approach will probably be easier to implement, and also give a better UX since users can just preload everything along with the charts data. 

Once we have the data we can then figure out how to display it throughout the survey. Ideally we would have tooltips inside the charts, as that's where library names are usually displayed the most.

**Comment by michaelrambeau** [comment]
The simplest solution is to generate a JSON file with all data we need.
So I created a "compact" version of the JSON file I build every day for bestof.js.org.

Here is a URL for tests: https://bestofjs-api-dev.firebaseapp.com/compact-list.json
Size: 60 KB gzipped.

The URL includes **all** projects available in bestof.js.org, but I could filter it to include only the relevant projects.

Here is a sample of data:

```json
{
  "count": 1051,
  "updated_at": "2017-11-09T12:42:29.883Z",
  "projects": [
    {
      "name": "RiotJS",
      "description": "Simple and elegant component-based UI library",
      "homepage": "http://riotjs.com",
      "slug": "riotjs",
      "github": "riot/riot",
      "stars": 12520
    },
    {
      "name": "Aurelia",
      "description": "The aurelia framework brings together all the required core aurelia libraries into a ready-to-go application-building platform.",
      "homepage": "",
      "slug": "aurelia",
      "github": "aurelia/framework",
      "stars": 10232
    },
    {
      "name": "Angular 1",
      "description": "AngularJS - HTML enhanced for web apps!",
      "homepage": "https://angularjs.org",
      "slug": "angular-1",
      "github": "angular/angular.js",
      "stars": 57472
    }
  ]
```

**Comment by SachaG** [comment]
Yeah I think it'd be important to filter them down to only the ones we need. Can we get a list easily? Also we need to make sure we use the same keys/slugs/ids.

**Comment by michaelrambeau** [comment]
OK @SachaG I'm going to filter the list, it makes non-sense to get data about all projects.

The slugs are the one I use in Best of JS but to create project URLs (E.g. https://bestof.js.org/projects/angular-1) but I can adjust them.

**Comment by SachaG** [comment]
I think it shouldn't be too hard to make sure we use the same slugs? Or do we need some kind of conversion table?

**Comment by michaelrambeau** [comment]
I updated the JSON file here: https://bestofjs-api-dev.firebaseapp.com/compact-list.json
Now it only includes 43 projects, those mentioned in the survey's question.

**Comment by SachaG** [comment]
Could we also add the "others answers" projects?

**Comment by SachaG** [comment]
Also maybe include a link back to the bestofjs page?

**Comment by michaelrambeau** [comment]
Is there a place where I can look up all projects mentioned in the `answers` responses ?
Or it's maybe simpler that I create this list my myself by checking all projects mentioned in "others" pages from http://st4t30fjs.surge.sh/ ?

FYI here is the JSON file I created to generate the API for StateOfJS; https://github.com/michaelrambeau/bestofjs-batches/blob/master/batches/build-data/stateofjs2017.json
So I can update it adding all other projects mentioned by the users.

About the link to the project's page in bestofjs, it's `https://bestof.js.org/projects/:slug`, I didn't want to include yjr full URL in the JSON response to make the response smaller, does it make sense?

**Comment by SachaG** [comment]
Other notes: render X & Y axis labels in React instead of in SVG; put axis above charts.

**Comment by SachaG** [comment]
@michaelrambeau could we add aliases to the JSON? For example in our data Vue is named `Vue` instead of `Vue.JS` in the JSON, Angular is `Angular` instead of `Angular 1`, etc.

Or else, we need to add the aliases in the results data somehow…?

**Comment by SachaG** [comment]
OK for now I'll just do this in our code:

```
export const aliases = {
    Vue: 'Vue.JS',
    Angular: 'Angular 1'
}
```

**Comment by SachaG** [comment]
WIP :)

![https://d3vv6lp55qjaqc.cloudfront.net/items/1D1D2L2Z0B2041151L1T/Screen%20Recording%202017-11-22%20at%2012.31%20PM.gif?X-CloudApp-Visitor-Id=f25ee64a8f9b32be400086060540ffac&v=a4298ef3](https://d3vv6lp55qjaqc.cloudfront.net/items/1D1D2L2Z0B2041151L1T/Screen%20Recording%202017-11-22%20at%2012.31%20PM.gif?X-CloudApp-Visitor-Id=f25ee64a8f9b32be400086060540ffac&v=a4298ef3)

**Comment by plouc** [comment]
:+1:

**Comment by SachaG** [comment]
I've got it working vertically as well, we just need to clean the source data and/or the json and add all the "others" answer:

![https://d3vv6lp55qjaqc.cloudfront.net/items/173P030O0H3A271G200s/Screen%20Shot%202017-11-22%20at%2014.54.06.png?X-CloudApp-Visitor-Id=43642&v=174791ef](https://d3vv6lp55qjaqc.cloudfront.net/items/173P030O0H3A271G200s/Screen%20Shot%202017-11-22%20at%2014.54.06.png?X-CloudApp-Visitor-Id=43642&v=174791ef)

**Comment by michaelrambeau** [comment]
Good job Sacha! I'm going to work on the API and add the missing projects and the aliases, taking advantage of the national holiday tomorrow 😀.

**Comment by michaelrambeau** [comment]
@SachaG I've just noticed that you renamed both `Angular 1` and `Vue.js` (previously in _State of JS_ it was `Angular` and `Vue`)... which means I have to revert the changes I did previously in the JSON used to display _Best of JavaScript_ data?

**Comment by SachaG** [comment]
Oh I don't know, my renaming is very easy to disable if it's messing with your side of things. In any case we should ideally make sure we use the "real" name for each library, whatever it is.
