### ISSUE TITLE
slightly improve Google Font load time with preconnect

### ISSUE THREAD

**Issue by coliff** [StateOfJS/StateOfJS#122]
I suggest to add `<link rel="preconnect" href="https://fonts.gstatic.com/" crossorigin>` in the head so that it does a DNS lookup sooner. Can reduce load time by approx 100 milliseconds.
REF: https://www.cdnplanet.com/blog/faster-google-webfonts-preconnect/

**Comment by plouc** [comment]
@coliff, thank you, fixed by https://github.com/StateOfJS/StateOfJS/commit/5c0000bb2e1e4e02e7b61ffd1e2b6b5bfebf62b0
