### ISSUE TITLE
England -> UK

### ISSUE THREAD

**Issue by SachaG** [StateOfJS/StateOfJS#128]
> Not a question but a suggestion. I live in England and am very aware that the residents of Scotland and Wales don't like to be classed as "English". You might want to change the title to the more neutral (and correct) Britain, Great Britain, GB, United Kingdom, or UK.

**Comment by plouc** [comment]
Fixed by https://github.com/StateOfJS/StateOfJS/commit/f44145482b61b0da3501c2b0c7b0ad46b96bc3d4
