### ISSUE TITLE
Salary charts: data should be weighed

### ISSUE THREAD

**Issue by plouc** [StateOfJS/StateOfJS#14]
Salary data should be weighed to cancel out framework popularity. Otherwise more popular frameworks will always show up as the most popular answers for every salary slice.

**Comment by SachaG** [comment]
Oh also a common remark is that salary ranges don't mean anything without the country. Maybe we should limit salaries to US only, to ensure they are consistent? 

For example, let's imagine a situation where Polymer is somewhat popular in Saudi Arabia where entry-level developers are paid $200k a month. This would skew the results when you view the "200k" bracket and make people think Polymer devs get paid a lot worldwide, even though $200k is a low salary for Saudi Arabia.

**Comment by SachaG** [comment]
https://en.wikipedia.org/wiki/Phi_coefficient

**Comment by SachaG** [comment]
Conclusion: use stacked chart instead.

**Comment by SachaG** [comment]
Reopening this because we still need to decide if we should filter salary data per country or just for the US.

**Comment by SachaG** [comment]
Thinking about it some more, I think people will definitely ask us for per-country salary data. We should consider doing it unless it really adds too much time and/or weight to the JSON.

**Comment by plouc** [comment]
Should be fine IMO, we just need to find a good selector library because we'll probably end up with many countries, `react-select` is the most popular one, what do you think?

**Comment by SachaG** [comment]
How about something like this for the UI?

![https://d3vv6lp55qjaqc.cloudfront.net/items/0I2Z111Y0u1l2I112o2x/Screen%20Shot%202017-11-23%20at%2016.06.01.png?X-CloudApp-Visitor-Id=43642&v=017f38f4](https://d3vv6lp55qjaqc.cloudfront.net/items/0I2Z111Y0u1l2I112o2x/Screen%20Shot%202017-11-23%20at%2016.06.01.png?X-CloudApp-Visitor-Id=43642&v=017f38f4)

Not sure we need `react-select`, maybe a normal select would work?

**Comment by plouc** [comment]
it was just for UX, to be able to easily find our country, but you're right maybe we can start with simple select.

**Comment by plouc** [comment]
IMHO It's confusing to have the averages below legends

**Comment by SachaG** [comment]
OK, maybe averages are not a good idea. Or else we find a better way to display them? Maybe connect them more to the chart visually, or only show them when hovering on a bar?

**Comment by plouc** [comment]
some kind of marker on each staked bar at average point could be less intrusive, but it's not supported by nivo, you can only have markers for the whole axis

**Comment by plouc** [comment]
or integrated with the libraries' name `React avg. $56K`
