### ISSUE TITLE
Breakdown tabels calculations

### ISSUE THREAD

**Issue by Dania-abdul** [StateOfJS/StateOfJS#150]
There is a mistake in the calculation; the numbers are not relatively correct switching from Percents to Counts in the Breakdown tables, please check screenshots attached below.

![screenshot 2018-11-28 at 17 19 32](https://user-images.githubusercontent.com/43537934/49206013-009f4900-f3b1-11e8-8ddb-857dbaacdbe3.png)
![screenshot 2018-11-28 at 17 20 19](https://user-images.githubusercontent.com/43537934/49206015-009f4900-f3b1-11e8-8568-906291724dee.png)

**Comment by plouc** [comment]
@Dania-abdul it's the percentage among users of the tool (vertical)
