### ISSUE TITLE
State of JS Dataviz Contest

### ISSUE THREAD

**Issue by SachaG** [StateOfJS/StateOfJS#151]
Submit your entries for the State of JavaScript 2018 data visualization contest. For each entry, submit: 

- A link to the entry.
- A link to a Twitter account where you can be reached (please follow [@SachaGreif](https://twitter.com/sachagreif) so I can DM you).
- Your preferred t-shirt (men's or women's) and US shirt size. 

More info: https://medium.com/@sachagreif/announcing-the-state-of-javascript-2018-data-visualization-contest-4d75abad96c8

**Comment by PamPierceLearnAboutGreen** [comment]
https://twitter.com/LearnAboutGreen/status/1069972390602555393
@LearnAboutGreen
Female large first choice, male medium second choice.
Thanks for the data!

**Comment by SachaG** [comment]
@PamPierceLearnAboutGreen sorry, I couldn't find any link to a data visualization?

**Comment by PamPierceLearnAboutGreen** [comment]
I thought you just wanted a link back to your contest.


Pam Pierce
281 E 232nd St., Euclid, OH 44123-1531
440-341-0955  pam@learnaboutgreen.com<mailto:pam@learnaboutgreen.com>





________________________________

**Comment by marcin-wosinek** [comment]
same visualization, slighlty changed:
https://marcin-wosinek.github.io/js-viz-2/

**Comment by SachaG** [comment]
@marcin-wosinek thanks, that's interesting! What's the different between the two versions exactly?

@kinxiel this is awesome, really creative! I've never thought about using something like animation speed as a variable in a chart, but that's such a cool way to add an extra dimension!

**Comment by SachaG** [comment]
Oh and btw @marcin-wosinek we'll link to all of these from a blog post once we have a few more, so maybe you could add a little description to the chart(s) to explain what you're trying to show? Just to give people more context and also help me write the post :)

**Comment by rubnvp** [comment]
hi @SachaG ! is the contest until 2018-12-19 23:59 GMT or 2018-12-20 23:59 GMT (included 20 or not)? 🤔

**Comment by SachaG** [comment]
20 included. I'm going to extend the deadline until Jan 1 anyway because we've only had 2 entries so far…

**Comment by rubnvp** [comment]
Here goes mine! 😄
Demographic data exploration, click on things to apply filters and change graphs 😃   

- Demo: [https://rubnvp.github.io/state-of-js-2018-visualization/](https://rubnvp.github.io/state-of-js-2018-visualization/)
- Repo: [https://github.com/rubnvp/state-of-js-2018-visualization](https://github.com/rubnvp/state-of-js-2018-visualization)
- Twitter: @rubnvp: [https://twitter.com/rubnvp/](https://twitter.com/rubnvp/)
- T-shirt: Men L

It was a little pain to normalize country names so feel free to get them from the repo! (/js/normalizeCountry.js)

**Comment by friedjoff** [comment]
My attempt to visualize opinions of JS on a map.

- Demo: https://stateofjs.geops.de/
- Twitter: https://twitter.com/friedjoff
- T-Shirt: L (men)

**Comment by SachaG** [comment]
@friedjoff @thomasheyenbrock these are amazing! Thank so much for the awesome work~

**Comment by SachaG** [comment]
Just wanted to update everybody: I've been very busy with work and life in general so I haven't made progress on this, but the offer is still valid, I will contact the winners soon about that tshirt :)

**Comment by SachaG** [comment]
The contest results are in! Thanks to everybody who took part :)

https://medium.freecodecamp.org/three-more-ways-to-visualize-the-state-of-javascript-1f91ee452d07
