### ISSUE TITLE
Edit translation TODO by contributors

### ISSUE THREAD

**Issue by balazsorban44** [StateOfJS/StateOfJS#160]
OK, so this may be off topic, but maybe someone else has the same question. Now that I have opened a PR for the translation of a language, I was curious if there was a way to another language contributor to edit the top comment with the TODO list? It would be practical if everyone could mark their translation done, or each other's after a check. It is again not related to the project per se, more of a GitHub question. Anyone with an answer? :crossed_fingers:

**Comment by SachaG** [comment]
Sadly I don't think it's possible. Maybe if you give that other contributor write access to the repo, but even then I'm not sure.

**Comment by balazsorban44** [comment]
I think it's dependent on this repo, not the fork, cause the PR belongs to this one. We were thinking of setting everyone as an assignee to the pr, but even I don't have access to do that. If you don't think it's practical or possible for you to set people as assignees (if it even works..) , just close this repo.

**Comment by SachaG** [comment]
Let's see… 

- [ ] can you check this?
- [ ] what about this?

**Comment by balazsorban44** [comment]
No. So I'll just close this. We will find another way.
