### ISSUE TITLE
Country charts: focus more on relative counts

### ISSUE THREAD

**Issue by plouc** [StateOfJS/StateOfJS#17]
Absolute country counts will always follow population, so they'll be the same for every answer. Sorting the chart by relative count to see which countries use a given tech more than others might be more interesting.

**Comment by SachaG** [comment]
Also relative counts should be calculated based on total usage *per framework* to avoid charts like this where the bars clearly don't add up to 100%:

![https://d3vv6lp55qjaqc.cloudfront.net/items/2T1d1p2z401y2N0w1002/Screen%20Shot%202017-11-10%20at%2013.07.41.png?X-CloudApp-Visitor-Id=f25ee64a8f9b32be400086060540ffac&v=522a64d3](https://d3vv6lp55qjaqc.cloudfront.net/items/2T1d1p2z401y2N0w1002/Screen%20Shot%202017-11-10%20at%2013.07.41.png?X-CloudApp-Visitor-Id=f25ee64a8f9b32be400086060540ffac&v=522a64d3)

And we should also order the bars by relative counts.

**Comment by SachaG** [comment]
![https://d3vv6lp55qjaqc.cloudfront.net/items/430I36263d13372C2h1A/Frame.png?X-CloudApp-Visitor-Id=f25ee64a8f9b32be400086060540ffac&v=e01438e9](https://d3vv6lp55qjaqc.cloudfront.net/items/430I36263d13372C2h1A/Frame.png?X-CloudApp-Visitor-Id=f25ee64a8f9b32be400086060540ffac&v=e01438e9)

**Comment by plouc** [comment]
I've pushed something, but there are 2 implementations available, using bubble or treemap, you can just change the implementation in `/Users/raph/projects/soj/src/components/WorldwideUsage.js`.

**Comment by SachaG** [comment]
Nice work! Just for reference:

![https://d3vv6lp55qjaqc.cloudfront.net/items/0A2c1C3X263e0W3A2z1c/Screen%20Shot%202017-11-19%20at%2010.38.33.png?X-CloudApp-Visitor-Id=43642&v=711dda20](https://d3vv6lp55qjaqc.cloudfront.net/items/0A2c1C3X263e0W3A2z1c/Screen%20Shot%202017-11-19%20at%2010.38.33.png?X-CloudApp-Visitor-Id=43642&v=711dda20)

and

![https://d3vv6lp55qjaqc.cloudfront.net/items/0B141O400P3G392i1Q30/Screen%20Shot%202017-11-19%20at%2010.51.47.png?X-CloudApp-Visitor-Id=43642&v=0d24de3e](https://d3vv6lp55qjaqc.cloudfront.net/items/0B141O400P3G392i1Q30/Screen%20Shot%202017-11-19%20at%2010.51.47.png?X-CloudApp-Visitor-Id=43642&v=0d24de3e)

I think the bubble chart version looks nice, especially if we give each answer a different color. Sure, it's not super meaningful since it's more or less the same for each countries, but it looks good :)

One thing we could add is a line about how we picked the countries. Maybe something like "only countries with 100+ answers shown"?

**Comment by SachaG** [comment]
Oh actually maybe this is a view where some kind of correlation/relation could be useful. For example, if we calculate the average worldwide for, say React, we could then show darker or lighter circles for each country according to how much that country's React usage differs from the average. 

This way if you see a bright red circle you know it means a given country has stronger-than-usual React usage. The only tricky part would be calculating the deviation, but I can probably find a stats expert to just ask for the proper formula :)

**Comment by SachaG** [comment]
Btw what's the reasoning for using ResponsiveBubbleHtml vs ResponsiveBubble? Could we reuse ResponsiveBubble so that we can reuse our custom bubble node with the dynamic label font size?

**Comment by plouc** [comment]
@SachaG, I tried implementing current hovered node highlighting, but given we have 32 charts, it was barely usable, so I tried HTML implementation because it may offer better performance, but it didn't make any difference, so we can use the SVG implementation.

**Comment by SachaG** [comment]
Ok so here's what I'd like to try. Currently this is the data format:

```
        {
            "key": "United States",
            "doc_count": 5719,
            "Firebase": {
                "doc_count": 1488
            },
            "REST API": {
                "doc_count": 5039
            },
            "Relay/Relay Modern": {
                "doc_count": 139
            },
            "Apollo": {
                "doc_count": 310
            },
            "Redux": {
                "doc_count": 2712
            },
            "GraphQL": {
                "doc_count": 751
            },
            "Falcor": {
                "doc_count": 24
            },
            "MobX": {
                "doc_count": 243
            }
        },
```

I think first we should calculate a relative score by comparing the count for each library to the overall count for the country. So in this case GraphQL would have a score of `751/5719 = 0.131` for example.

Then we figure out the equivalent worldwide score, for GraphQL this would be `2794/23704 = 0.117`. 

We can then compare both scores to get the difference, in this case `0.131 - 0.117 = 0.014`. So this means GraphQL usage in the US is superior to the average by 0.014 points (or we can multiply by 100 and say 1.4 points to simplify it). We would then have a color scale that maps scores from -10 to +10 (for example). 

So ideally it would be possible to see right away that GraphQL usage is higher in the US compared to the average. A better example might be Vue, which clearly has a higher usage in China compared to the average. But with the circle sizes alone it might not jump out as much: 

![https://d3vv6lp55qjaqc.cloudfront.net/items/0g282i2y2D221n0Q3P3c/Screen%20Shot%202017-11-23%20at%2011.25.10.png?X-CloudApp-Visitor-Id=43642&v=ef6a6694](https://d3vv6lp55qjaqc.cloudfront.net/items/0g282i2y2D221n0Q3P3c/Screen%20Shot%202017-11-23%20at%2011.25.10.png?X-CloudApp-Visitor-Id=43642&v=ef6a6694)

Also another advantage of using colors is that it's more obvious for smaller libraries. For example Polymer will always have a small circle, but as you can see above that small circle is clearly bigger than average for Portugal.

**Comment by plouc** [comment]
<img width="1110" alt="capture d ecran 2017-12-01 a 15 03 15" src="https://user-images.githubusercontent.com/501642/33469903-d02cd9b6-d6a8-11e7-8ed4-bd9779032ff8.png">
