### ISSUE TITLE
Add question(s) re: adoption of new Ecmascript features

### ISSUE THREAD

**Issue by dtex** [StateOfJS/StateOfJS#187]
It would be helpful for standards bodies to have insight into the adoption rate of newly added features. Promises, Async/Await, Classes, SharedArrayBuffer, etc. While the results may not guide language design (that horse has left the barn), they could certainly influence documentation and API design.

Also, people might be more motivated to learn a feature if they see everyone else is learning it.

**Comment by SachaG** [comment]
Good point, for the State of CSS survey we added a Features category and we'll do the same for the next State of JS as well.
