### ISSUE TITLE
Missing privacy policy and GDPR violation

### ISSUE THREAD

**Issue by Kovah** [StateOfJS/StateOfJS#205]
I just saw that the StateOfJS survey now requires an account to be created to participate. As the creation of an account links personal identifiable information such as the email address to the saved results, you should take a quick look at the [GDPR](https://gdpr.eu/), because you are now violating them. As you also do not provide any privacy policy, no user can be certain that you collect any personal information to sell or share them afterwards.

The least you should do for your users and their trust, is to add a privacy policy that clearly states 
- what information is collected, 
- how it's linked to the survey results and 
- which involved parties have access to the data.

Please take this serious.

**Comment by SachaG** [comment]
Just added one, thanks for the reminder! Let me know what you think: https://survey.stateofjs.com/privacy-policy

**Comment by Kovah** [comment]
I'm not a lawyer, but looks somewhat good to me.
