### ISSUE TITLE
Salary/Experience: do we need both absolute and relative?

### ISSUE THREAD

**Issue by SachaG** [StateOfJS/StateOfJS#23]
Also I must be missing something, because I would've expected both charts to be the same? 

![https://d3vv6lp55qjaqc.cloudfront.net/items/471O2E220W3U1W2L2I1c/Screen%20Shot%202017-11-10%20at%2013.15.13.png?X-CloudApp-Visitor-Id=f25ee64a8f9b32be400086060540ffac&v=069502a0](https://d3vv6lp55qjaqc.cloudfront.net/items/471O2E220W3U1W2L2I1c/Screen%20Shot%202017-11-10%20at%2013.15.13.png?X-CloudApp-Visitor-Id=f25ee64a8f9b32be400086060540ffac&v=069502a0)

![https://d3vv6lp55qjaqc.cloudfront.net/items/1o023c3c272h063e0J1h/Screen%20Shot%202017-11-10%20at%2013.16.38.png?X-CloudApp-Visitor-Id=f25ee64a8f9b32be400086060540ffac&v=542df196](https://d3vv6lp55qjaqc.cloudfront.net/items/1o023c3c272h063e0J1h/Screen%20Shot%202017-11-10%20at%2013.16.38.png?X-CloudApp-Visitor-Id=f25ee64a8f9b32be400086060540ffac&v=542df196)

**Comment by plouc** [comment]
It's not just a number/percent switch, for the first one it's relative to the total count, for the second one, it's relative to the total for each segment, but maybe it's not intuitive.

**Comment by SachaG** [comment]
Yeah it's not intuitive, because even after thinking about it for 5 minutes I still don't get it…

**Comment by SachaG** [comment]
Conclusion: let's only keep relative mode (percents), but using the number of X users (React users, Angular users, etc.) as total so that we end up with 100%. 

Optionally, we can add a numbers/percent toggle or show the absolute numbers on hover.
