### ISSUE TITLE
Use patterns in charts?

### ISSUE THREAD

**Issue by SachaG** [StateOfJS/StateOfJS#27]
Cool idea: https://css-tricks.com/simple-patterns-for-separation/

**Comment by plouc** [comment]
I agree :), http://nivo.rocks/#/guides/patterns

**Comment by plouc** [comment]
<img width="727" alt="capture d ecran 2017-12-09 a 14 31 41" src="https://user-images.githubusercontent.com/501642/33792833-bd2e653c-dced-11e7-9148-4ee1764df9d3.png">
