### ISSUE TITLE
Salary and Experience: add average column

### ISSUE THREAD

**Issue by SachaG** [StateOfJS/StateOfJS#28]
It would be useful to add a column with the average for all frameworks for each section as a reference point.

**Comment by SachaG** [comment]
Also, we could calculate the per-column average. It wouldn't be very precise since we're using ranges, but it would still indicate something: 

![https://d3vv6lp55qjaqc.cloudfront.net/items/0N3H2s3b3g2s0q2s3R1t/Screen%20Shot%202017-11-23%20at%2015.11.29.png?X-CloudApp-Visitor-Id=43642&v=f769fe90](https://d3vv6lp55qjaqc.cloudfront.net/items/0N3H2s3b3g2s0q2s3R1t/Screen%20Shot%202017-11-23%20at%2015.11.29.png?X-CloudApp-Visitor-Id=43642&v=f769fe90)

The only thing is I'm not sure how this will work with responsiveness since it's outside the chart…

**Comment by plouc** [comment]
It could be inside it, and I think we need a legend for those values

**Comment by plouc** [comment]
I'm not sure about the colors as it seems it's diverging when it become lighter, which is not the case

**Comment by SachaG** [comment]
Agreed, I just wasn't sure how/where to put the legend. I can leave it as a temporary static mockup for now and we can fix it Saturday maybe?

**Comment by plouc** [comment]
Added average column, columns are now sorted by average & percentages have been fixed to reach exactly 100%.
