### ISSUE TITLE
New Chart: Number of Libraries Used

### ISSUE THREAD

**Issue by SachaG** [StateOfJS/StateOfJS#29]
I think it'd be great to see the breakdowns of how many developers use how many libraries for each section. 

So for example, for the front-end section we could have a donut chart showing which percentage has only used one library, which percentage has used two, three, etc. all the way to people who have tried all 9 options. 

I don't think the data would be that hard to aggregate, and I think the chart could be pretty meaningful? ("oh, most people have tried four of these libraries but I've only tried two, maybe I should make more time to study new technologies!")

**Comment by plouc** [comment]
by "used" you mean willing to continue to do so, or both "would" & "would not"?

**Comment by SachaG** [comment]
Both I think, since in this case it's more about showing how many libraries people try.

**Comment by plouc** [comment]
Do we need the corresponding libraries, or is it just a matter of *how many*?

**Comment by SachaG** [comment]
Just how many.

**Comment by plouc** [comment]
<img width="757" alt="capture d ecran 2017-12-03 a 15 54 02" src="https://user-images.githubusercontent.com/501642/33523115-3e393162-d842-11e7-9120-6a6ba136dbec.png">

**Comment by plouc** [comment]
I have to adjust colors to match our current theme

**Comment by plouc** [comment]
<img width="840" alt="capture d ecran 2017-12-03 a 16 22 03" src="https://user-images.githubusercontent.com/501642/33523290-23bf7ac2-d846-11e7-8dbf-cddbec470e03.png">

**Comment by plouc** [comment]
fixed by https://github.com/StateOfJS/StateOfJS/commit/c0fa423618dbe5c5b6403b66c52ac9abc426a4a6
