### ISSUE TITLE
Visual Bugs

### ISSUE THREAD

**Issue by SachaG** [StateOfJS/StateOfJS#33]
Just writing down all the small visual bugs/issues.

- [x] Overlap issues with bar labels

![https://d3vv6lp55qjaqc.cloudfront.net/items/0b2M1W021P1B190C3A04/Screen%20Shot%202017-11-24%20at%2011.53.00.png?X-CloudApp-Visitor-Id=43642&v=b6be4cd9](https://d3vv6lp55qjaqc.cloudfront.net/items/0b2M1W021P1B190C3A04/Screen%20Shot%202017-11-24%20at%2011.53.00.png?X-CloudApp-Visitor-Id=43642&v=b6be4cd9)

- [x] Alignment issue with X axis

![https://d3vv6lp55qjaqc.cloudfront.net/items/2S333h3x3x213c1W3T1J/Screen%20Shot%202017-11-24%20at%2011.53.39.png?X-CloudApp-Visitor-Id=43642&v=85c9f9d9](https://d3vv6lp55qjaqc.cloudfront.net/items/2S333h3x3x213c1W3T1J/Screen%20Shot%202017-11-24%20at%2011.53.39.png?X-CloudApp-Visitor-Id=43642&v=85c9f9d9)

- [ ] Overlap issue with horizontal bar labels for short bars (Other Tools page)

![https://d3vv6lp55qjaqc.cloudfront.net/items/2P2y3N2p2q410Y1C080o/Screen%20Shot%202017-11-24%20at%2011.54.40.png?X-CloudApp-Visitor-Id=43642&v=b5cc57de](https://d3vv6lp55qjaqc.cloudfront.net/items/2P2y3N2p2q410Y1C080o/Screen%20Shot%202017-11-24%20at%2011.54.40.png?X-CloudApp-Visitor-Id=43642&v=b5cc57de)

**Comment by SachaG** [comment]
- [ ] "Aggregated" word not great… replace with "Average" or "Overall"?

**Comment by SachaG** [comment]
- [ ] "No Front-end Framework" -> "No Framework"

![https://d3vv6lp55qjaqc.cloudfront.net/items/0k2Y333k2u3F1X2j3R1e/Screen%20Shot%202017-12-02%20at%2018.16.43.png?X-CloudApp-Visitor-Id=f25ee64a8f9b32be400086060540ffac&v=45999ec5](https://d3vv6lp55qjaqc.cloudfront.net/items/0k2Y333k2u3F1X2j3R1e/Screen%20Shot%202017-12-02%20at%2018.16.43.png?X-CloudApp-Visitor-Id=f25ee64a8f9b32be400086060540ffac&v=45999ec5)

**Comment by SachaG** [comment]
- [ ] Emojis in lib descriptions:

![https://d3vv6lp55qjaqc.cloudfront.net/items/1l0A1m1q2n160b392E3v/%5Be9c5ec5af6abdbccb31231ad3a66ea8c%5D_Screen%2520Shot%25202017-12-02%2520at%252018.39.56.png?X-CloudApp-Visitor-Id=f25ee64a8f9b32be400086060540ffac&v=bc6f0c03](https://d3vv6lp55qjaqc.cloudfront.net/items/1l0A1m1q2n160b392E3v/%5Be9c5ec5af6abdbccb31231ad3a66ea8c%5D_Screen%2520Shot%25202017-12-02%2520at%252018.39.56.png?X-CloudApp-Visitor-Id=f25ee64a8f9b32be400086060540ffac&v=bc6f0c03)

**Comment by michaelrambeau** [comment]
I'm going to include the fix for the emojis in the PR #36.
