### ISSUE TITLE
Blinking yellow links

### ISSUE THREAD

**Issue by brettdh** [StateOfJS/StateOfJS#47]
The frenetic blinking yellow hover on every link literally makes it painful to navigate what is otherwise an awesome and wonderful site. Please settle that down.

**Comment by SachaG** [comment]
It's a design choice I guess… I can certainly understand that it wouldn't be for everybody. I'll look into it, if it turns out that it's an accessibility issue I will change it, but otherwise I will probably leave it like that unless we really get a ton of complaints here :)

**Comment by SachaG** [comment]
Seems like it might be an issue actually: 

http://www.washington.edu/accessibility/checklist/flashing-content/
https://www.webaccessibility.com/best_practices.php?best_practice_id=353

Don't really know much about epilepsy but that would be a good reason to change them…

**Comment by brettdh** [comment]
Thanks! 👏
