### ISSUE TITLE
[Question] What for library/framework was used initially? 

### ISSUE THREAD

**Issue by sparcut** [StateOfJS/StateOfJS#52]
If I'm not mistaken, State of JS has used a library or framework that enables the creataion of sleek and simple forms/surveys. (can't remember if recently or in the past.) 
I've been trying to find it, though unsuccessful. 

I'd seen it used before, it fills the browser window, responsive across devices, keyboard focused (can be used with keyboard only), only shows a question at a time, large but simplistic styling.

**Comment by michaelrambeau** [comment]
@sparcut Actually the survey form is an online service: https://www.typeform.com/

Just in case, here is an opensource alternative: https://www.tellform.com/

**Comment by sparcut** [comment]
@michaelrambeau Perfect, just what I was looking for.

Also cheers for the opensource alt!
