### ISSUE TITLE
Chord Diagram is too complicated

### ISSUE THREAD

**Issue by Everettss** [StateOfJS/StateOfJS#54]
Chord Diagram as a representation for [connections](https://stateofjs.com/2017/connections/) look great but it doesn't bring more value than traditional heat map from the last year. Using Chord Diagram breaks the rule of “KISS” for “Keep it Simple, Stupid” more about of this [here](https://questionsindataviz.com/2016/12/05/is-there-a-place-for-chord-charts-in-data-visualisation/) and [here](http://www.vizwiz.com/2016/12/makeover-monday-global-flow-of-people.html). The heat map is so much easier for detail analysis. Also, heat map will allow for easier comparison between years.

I propose to create a switch for changing between **chord diagram** and **heat map**.

**Comment by SachaG** [comment]
I think it makes up for the added complexity with its coolness :)
