### ISSUE TITLE
[Discussion] Domain & URL structure for each year

### ISSUE THREAD

**Issue by SachaG** [StateOfJS/StateOfJS#55]
Currently, we have the following URL structure:

| **URL**            | **Content**      |
|--------------------|------------------|
| stateofjs.com      | current homepage |
| 2017.stateofjs.com/| 2017 site     |
| stateofjs.com/2017 | 2017 results (but with current styling)     |

Which is a mess because links still point to `stateofjs.com/2017` which can be broken by the new styles/features added for the 2018 version. 

Question: should we do: 

# Solution A

| **URL**            | **Content**      |
|--------------------|------------------|
| stateofjs.com      | current homepage |
| stateofjs.com/2017 | 2017 results     |
| stateofjs.com/2018 | 2018 results     |

### Pros: 

- Single monorepo
- Single deploy target
- No broken links
- Possible to preload results when user is on homepage
- Potentially easier to make comparisons between each year's data

### Cons: 

- Requires maintaining backwards compatibility between each year
- Bundle has to contain data/components/etc. for all years
- Not possible to have different styling for each year 😡

Or:

# Solution B

| **URL**            | **Content**      |
|--------------------|------------------|
| stateofjs.com      | current homepage |
| 2017.stateofjs.com/| 2017 results     |
| 2018.stateofjs.com/| 2018 results     |

### Pros: 

- Completely independent sites
- No risk of breaking previous year's results

### Cons: 

- Requires maintaining multiple repos or branches, and multiple deploy targets
- No preloading

**Comment by SachaG** [comment]
For now I think a good enough fix is redirecting https://stateofjs.com/2017/front-end/results/ to https://2017.stateofjs.com/2017/front-end/results/

**Comment by plouc** [comment]
monorepo :)
