### ISSUE TITLE
[New Feature] Chart for showing main reasons behind preferences

### ISSUE THREAD

**Issue by SachaG** [StateOfJS/StateOfJS#56]
Now that people can give their reason why they like/dislike each library we need a new chart to show the results: 

![https://d3vv6lp55qjaqc.cloudfront.net/items/141P103v2G1P060e042T/Screen%20Shot%202018-09-06%20at%2017.09.03.png?X-CloudApp-Visitor-Id=43642&v=da02c81b](https://d3vv6lp55qjaqc.cloudfront.net/items/141P103v2G1P060e042T/Screen%20Shot%202018-09-06%20at%2017.09.03.png?X-CloudApp-Visitor-Id=43642&v=da02c81b)

**Comment by plouc** [comment]
We could use some kind of partition layout.

<img width="593" alt="capture d ecran 2018-09-06 a 18 58 32" src="https://user-images.githubusercontent.com/501642/45150977-077e4b80-b208-11e8-8dae-6caa9b09bee4.png">

The first column being the item ('React'), the second one containing preference ('used', 'not used', …) and the third one containing reasons. the second and third column items will be sized according to number of responses.

**Comment by plouc** [comment]
If a specific item is too small to display its label, we could rely on a tooltip.

**Comment by SachaG** [comment]
We only ask for the reason for used/not used so the second column would always only have 2 items. So I think it makes more sense to just show two separate charts.

**Comment by plouc** [comment]
We can include other preferences, they'll have no items in third column.

**Comment by SachaG** [comment]
See https://stateofjs.github.io/2018-charts-catalogue/?selectedKind=Reasons%20behind%20libraries%20result&selectedStory=Bar&full=0&addons=0&stories=1&panelRight=0

I think to simplify the UI a bit we can decide to always just sort by rank.

**Comment by SachaG** [comment]
Current version:

![https://d3vv6lp55qjaqc.cloudfront.net/items/2X03352c3l3o1A0c0X2a/Screen%20Shot%202018-10-13%20at%209.53.42.png?X-CloudApp-Visitor-Id=43642&v=247dd46d](https://d3vv6lp55qjaqc.cloudfront.net/items/2X03352c3l3o1A0c0X2a/Screen%20Shot%202018-10-13%20at%209.53.42.png?X-CloudApp-Visitor-Id=43642&v=247dd46d)

Notes:

- Find better title for the chart
- What scale do the axis use?
- Labels are a bit small
- Takes too much space horizontally?
- Does it make sense to keep both likes/dislikes on the same level since they're not really related?

**Comment by SachaG** [comment]
- [ ] put legends on left
- [ ]  highlight on hover
- [ ] larger bars

![https://d3vv6lp55qjaqc.cloudfront.net/items/1n3p0n1Q2I1734330N3Q/Screen%20Shot%202018-10-15%20at%2014.06.48.png?X-CloudApp-Visitor-Id=43642&v=f9a9c90a](https://d3vv6lp55qjaqc.cloudfront.net/items/1n3p0n1Q2I1734330N3Q/Screen%20Shot%202018-10-15%20at%2014.06.48.png?X-CloudApp-Visitor-Id=43642&v=f9a9c90a)
