### ISSUE TITLE
[New Feature] Comparison with previous year

### ISSUE THREAD

**Issue by SachaG** [StateOfJS/StateOfJS#57]
Could we find a way to include a comparison with 2017 to show the trend, when applicable?

- [x] Vertically space out chart and legend:
- [x] remove legend frame
- [x] shorten legend wording
- [x] add dots on chart
- [x] add ability to highlight a specific datum (for example `never heard of it`) when we hover a legend

**Comment by SachaG** [comment]
![https://d3vv6lp55qjaqc.cloudfront.net/items/0x0i2R2O3X210g1x1u3Q/Screen%20Shot%202018-10-13%20at%209.58.30.png?X-CloudApp-Visitor-Id=43642&v=8eee87a7](https://d3vv6lp55qjaqc.cloudfront.net/items/0x0i2R2O3X210g1x1u3Q/Screen%20Shot%202018-10-13%20at%209.58.30.png?X-CloudApp-Visitor-Id=43642&v=8eee87a7)

- We should make it more obvious that you can hover over each year to get the data. Maybe show a vertical hover zone? Or ideally show the datapoints on the chart directly? (could be difficult because of spacing constraints)
- The tooltip should use the same scale (percent?) as the axis. Especially since total number of respondents vary from year to year. 
-

**Comment by SachaG** [comment]
[ ] Vertically space out chart and legend:

![https://d3vv6lp55qjaqc.cloudfront.net/items/452g242c3d0O2O1F0A41/Screen%20Shot%202018-10-15%20at%2014.03.07.png?X-CloudApp-Visitor-Id=43642&v=48f0b1ef](https://d3vv6lp55qjaqc.cloudfront.net/items/452g242c3d0O2O1F0A41/Screen%20Shot%202018-10-15%20at%2014.03.07.png?X-CloudApp-Visitor-Id=43642&v=48f0b1ef)

**Comment by plouc** [comment]
<img width="944" alt="capture d ecran 2018-10-15 a 16 57 59" src="https://user-images.githubusercontent.com/501642/46937179-83877100-d09b-11e8-8a72-f318ea13e55e.png">

**Comment by plouc** [comment]
I've made another test keeping the frame around the legends

<img width="894" alt="capture d ecran 2018-10-16 a 09 30 35" src="https://user-images.githubusercontent.com/501642/46985619-5502a800-d126-11e8-9feb-dc9753317e37.png">

**Comment by plouc** [comment]
- [ ] add ability to highlight a specific datum (for example `never heard of it`) when we hover a legend
