### ISSUE TITLE
Other Tools

### ISSUE THREAD

**Issue by SachaG** [StateOfJS/StateOfJS#63]
The "other tools" page has more content this year: 

- Other Languages
- Browser APIs
- Build Tools
- Utility Libraries
- Text Editors

**Comment by plouc** [comment]
Data is now up to date and injected in the template, we now must translate tools

**Comment by plouc** [comment]
I close this in favor of https://github.com/StateOfJS/StateOfJS/issues/95

**Comment by plouc** [comment]
In fact we should also update the intro accordingly
