### ISSUE TITLE
Demographics page

### ISSUE THREAD

**Issue by SachaG** [StateOfJS/StateOfJS#64]
Since we collected a bit more demographics info this time (such as gender) it'd be interesting to have a new page for that. 

We could also present general stats for salary ranges/years of experience/company size/etc.

**Comment by SachaG** [comment]
- [ ] Replace with a single global gender waffle chart

![https://d3vv6lp55qjaqc.cloudfront.net/items/0s3U1z1N0N2z1Q3o0X0I/Screen%20Shot%202018-10-15%20at%2014.43.43.png?X-CloudApp-Visitor-Id=43642&v=84665065](https://d3vv6lp55qjaqc.cloudfront.net/items/0s3U1z1N0N2z1Q3o0X0I/Screen%20Shot%202018-10-15%20at%2014.43.43.png?X-CloudApp-Visitor-Id=43642&v=84665065)

**Comment by SachaG** [comment]
- [ ] salaries per country on map

**Comment by plouc** [comment]
Fixed, however I wasn't able to generate the screenshots for the charts.
