### ISSUE TITLE
Happiness

### ISSUE THREAD

**Issue by SachaG** [StateOfJS/StateOfJS#69]
Show comparison with previous year?

![https://d3vv6lp55qjaqc.cloudfront.net/items/1Z1b19332d470b1i2F0C/Screen%20Shot%202018-10-15%20at%2014.52.33.png?X-CloudApp-Visitor-Id=43642&v=4cf276a7](https://d3vv6lp55qjaqc.cloudfront.net/items/1Z1b19332d470b1i2F0C/Screen%20Shot%202018-10-15%20at%2014.52.33.png?X-CloudApp-Visitor-Id=43642&v=4cf276a7)

**Comment by SachaG** [comment]
Concept: 

![https://d3vv6lp55qjaqc.cloudfront.net/items/0L2b0a372C3Z3k3I352x/Screen%20Shot%202018-10-15%20at%2014.57.46.png?X-CloudApp-Visitor-Id=43642&v=571b8c0d](https://d3vv6lp55qjaqc.cloudfront.net/items/0L2b0a372C3Z3k3I352x/Screen%20Shot%202018-10-15%20at%2014.57.46.png?X-CloudApp-Visitor-Id=43642&v=571b8c0d)

**Comment by plouc** [comment]
I close this issue, but we don't have the comparison feature as we didn't came up to a viable solution (the delta from one year to the next is too small). maybe we can add another line chart below to show the trend?

**Comment by SachaG** [comment]
Let's do it next year.
