### ISSUE TITLE
Fix bar chart value contrast

### ISSUE THREAD

**Issue by SachaG** [StateOfJS/StateOfJS#78]
![https://d3vv6lp55qjaqc.cloudfront.net/items/1o0w2J0o251z3n0S343P/Screen%20Shot%202018-11-02%20at%209.06.15.png?X-CloudApp-Visitor-Id=43642&v=dc986c24](https://d3vv6lp55qjaqc.cloudfront.net/items/1o0w2J0o251z3n0S343P/Screen%20Shot%202018-11-02%20at%209.06.15.png?X-CloudApp-Visitor-Id=43642&v=dc986c24)

**Comment by plouc** [comment]
Fixed as we no more display values.
