### ISSUE TITLE
Testing section conclusion

### ISSUE THREAD

**Issue by SachaG** [StateOfJS/StateOfJS#81]
> The testing space is a bit of an oddity: while the other parts of the JavaScript ecosystem have been slowly settling down around a few dominant solutions, testing is still very fragmented: lots of different, complementary tools share the pie.

**Comment by michaelrambeau** [comment]
## First draft

Commenting https://2018.stateofjs.com/testing/conclusion/

![image](https://user-images.githubusercontent.com/5546996/47947007-d72d0200-df57-11e8-9931-74d5a31c3149.png)

With 10K users, the survey confirms that _Mocha_ is still the most used unit testing framework.
Being around for a long time, it has the largest ecosystem and most of the Node.js developers know it.

_Jest_ follows closely in terms of usage but it has a very high satisfaction rate: 96% versus 82%.

As a side note, 96% is the second highest satisfaction in the whole survey this year (only ES6 got a better mark!).

It shows that developers really appreciate the efforts made by Facebook to provide a a full-featured testing framework that can be used to test both front-end (it was intended to test React components, in the beginning) and back-end code, without requiring configuration.

_Storybook_ got the second highest satisfaction rate of the category. It's not a testing framework but a solution to let developers test their components in isolation. It was first intended to React developers but it supports now Vue.js and AngularJS. It comes with a lot of handy plugins to customize the functionalities.

Globally, developers are satisfied by their testing solution, no framework got a satisfaction ratio lower than 68%.

**Comment by SachaG** [comment]
Any update?

**Comment by michaelrambeau** [comment]
I've updated the conclusion in this branch: 

https://github.com/StateOfJS/StateOfJS/tree/feature/update-section-conclusions

I can adjust if you think it's too long or not interesting.
