### ISSUE TITLE
Mobile & Desktop section conclusion

### ISSUE THREAD

**Issue by SachaG** [StateOfJS/StateOfJS#82]
> As JavaScript expands beyond the boundaries of the browser, we see a familiar pattern play out: yesterday's dominant tool, Cordova, now suffers from a pretty poor satisfaction ratio; while React Native is doing much better and fast catching up.

> Electron is also worth mentioning, as its adoption by major players such as Slack or Atom has let to notable performance improvements in recent years.

**Comment by michaelrambeau** [comment]
## First draft

![image](https://user-images.githubusercontent.com/5546996/47946774-b367bd00-df53-11e8-9f61-d1e5f4ea8e27.png)


_React Native_ and _Electron_ are the two leading solutions to build respectively mobile and desktop applications from web technologies.
Coincidentally we got similar numbers in both satisfaction rate and number of users (around 5K).

_Electron_ versatility (it can work with any UI framework even if it's often associated with React or Vue.js) may explain the highest satisfaction ratio of the category (87%).
There were a lot of talks about _React Native_ a few months ago when AirBnb published an article explaining why they decided to drop _React Native_ for their next production in favor of _Native Apps_.
Despite that news, _React Native_ satisfaction ratio (84%) is very high.

Talking about _Native Apps_, it's interesting to note that we got the 3rd satisfaction rate (79%), especially if you consider that the survey targets JavaScript developers (and not Android or Swift developers)

_Cordova_ technology has the highest usage number but its low satisfaction rate shows clearly it's no more the first choice to build a mobile application.

**Comment by SachaG** [comment]
Same general feedback as the other one, it's a great description of the results but ideally we should try to also provide more insight that people might not get from the data itself.

**Comment by michaelrambeau** [comment]
We could mention Flutter maybe in the last part of the conclusion:

The future of cross-platform mobile frameworks may be [Flutter](https://flutter.io/) from Goggle.
Instead of building a JavaScript "bridge" like _React Native_ does, it compiles to true native code. But the code is written in Dart language, so _React Native_ will be still relevant to most of JavaScript developers already familiar with the React system.

**Comment by michaelrambeau** [comment]
We could also take advantage of the conclusion to mention "Weex" project (that was not included in the survey)?

As an alternative to React Native, for developers who want to write cross-platform applications in JavaScript but without using React patterns, we could mention [Weex](https://weex.apache.org/) that let developers use the _Vue.js_ eco-system.

**Comment by SachaG** [comment]
Good ideas :)

**Comment by michaelrambeau** [comment]
I've updated the conclusion in this branch, mentioning `Carlo` project too.

https://github.com/StateOfJS/StateOfJS/tree/feature/update-section-conclusions
