### ISSUE TITLE
"Stacks" heatmap on tool page

### ISSUE THREAD

**Issue by SachaG** [StateOfJS/StateOfJS#85]
Reuse heatmap concept from 2016 on each individual tool page.

![https://d3vv6lp55qjaqc.cloudfront.net/items/1J3T3y2B0E1c1502193u/Screen%20Shot%202018-11-03%20at%2012.35.28.png?X-CloudApp-Visitor-Id=43642&v=9a8d64d6](https://d3vv6lp55qjaqc.cloudfront.net/items/1J3T3y2B0E1c1502193u/Screen%20Shot%202018-11-03%20at%2012.35.28.png?X-CloudApp-Visitor-Id=43642&v=9a8d64d6)

**Comment by plouc** [comment]
<img width="595" alt="screenshot 2018-11-06 at 18 08 01" src="https://user-images.githubusercontent.com/501642/48053870-14f78800-e1ef-11e8-8ece-e03cfd386292.png">
