### ISSUE TITLE
Multiple Language Support

### ISSUE THREAD

**Issue by SachaG** [StateOfJS/StateOfJS#87]
This is more of a long-term project since the UI is not currently internationalized, but assuming we had translators on board it could be a good idea to translate the results site. 

This could be especially effective in letting us reach new audiences for next year's survey. If you'd like to help us with this, please leave a comment here mentioning the language(s) you'd like to help translate to.

**Comment by ricardoerl** [comment]
I can help with Spanish 🖐️

**Comment by rpesciotta** [comment]
I can help with Brazilian Portuguese

**Comment by InamTaj** [comment]
I can help with Urdu language.

**Comment by rmngrc** [comment]
I can help with Spanish from Spain too :)

**Comment by ManoelLobo** [comment]
I can help with PT-Br, like @rpesciotta

**Comment by jakubjo** [comment]
I can help with German.

**Comment by giuseongit** [comment]
I can help with Italian.

**Comment by fabioscsilva** [comment]
I can help with Portuguese - Portuguese

**Comment by SoulierAntoine** [comment]
I can help with French. :-)

**Comment by sin** [comment]
I can help with Polish.

**Comment by PBartrina** [comment]
I can help with both Spanish (Spain) and Catalan (Spain)

**Comment by csfcampos** [comment]
Hi! I can help with European Portuguese

**Comment by theuselessdeveloper** [comment]
I can help with Romanian, Russian and Italian

**Comment by nikosgram13** [comment]
Hello, I can help with Greek.

**Comment by fernandesrenan** [comment]
I, too, can help with Brazilian Portuguese.

**Comment by agatac** [comment]
I can help with Polish :poland:

**Comment by dor-shtaif-rapidapi** [comment]
I would help with Hebrew (Israel) :)

**Comment by shtaif** [comment]
I would help with Hebrew (Israel) :)

**Comment by FabioGuerreiro** [comment]
> I can help with Portuguese - Portuguese

I can also give a hand with that (pt-PT)

**Comment by csfcampos** [comment]
> > I can help with Portuguese - Portuguese
> 
> I can also give a hand with that (pt-PT)

I can also help with pt-PT

**Comment by ysm0622** [comment]
I can help with Korean 🇰🇷

**Comment by Plotisateur** [comment]
I can also help in French ! :)

**Comment by joelalejandro** [comment]
Also available for Spanish :)

**Comment by rafaeelaudibert** [comment]
Count on me for Brazilian Portuguese :smiley:

**Comment by kamalyzl** [comment]
Español!

**Comment by sarahdayan** [comment]
I can help with French 🇫🇷

**Comment by remusa** [comment]
Available for Spanish too!

**Comment by alejandronanez** [comment]
Spanish here!

**Comment by lelbil** [comment]
I can help with Arabic :)

**Comment by S1ngS1ng** [comment]
I can help with Chinese 🇨🇳 , both simplified and traditional.

**Comment by kiwanska** [comment]
I can help with Polish 🇵🇱, strong community of devs there!

**Comment by santanaG** [comment]
I can help with Spanish.

**Comment by xfields** [comment]
> I can help with Chinese  , both simplified and traditional.

Available with Chinese too :cn:

**Comment by fbracht** [comment]
I can and would love to help (or even do the whole thing!) with **PT-BR** 🇧🇷.

I'm not an accomplished web developer even though I have studied a lot about the craft, but I do work mainly with localization efforts — currently doing Language Quality Evaluations for a pretty big tech company.

**Comment by robertgrzonka** [comment]
Next volunteer for polish 🙋🏼‍♂️

**Comment by dikyarga** [comment]
I will help for Bahasa Indonesia 🇮🇩

**Comment by raulfdm** [comment]
Hey Brazilians, count on me to help translate it to pt-BR 🇧🇷

**Comment by GISLearner** [comment]
I can hele with chinese

**Comment by yusufff** [comment]
I can help with Turkish 🤚

**Comment by MohamadKh75** [comment]
I can help with Persian 🇮🇷

**Comment by egaris** [comment]
I can help with Russian

**Comment by MatanBobi** [comment]
Can help with Hebrew (he-IL)

**Comment by usman87** [comment]
I can help with Urdu

**Comment by Schaemelhout** [comment]
I can help with Dutch

**Comment by frinyvonnick** [comment]
I can help with French too 😉

**Comment by Nyalab** [comment]
i also would love to help translating this survey in french 🙂

**Comment by andrey-semin** [comment]
Can help with Russian!

**Comment by SargoDarya** [comment]
German here able to help

**Comment by michaellopez** [comment]
My team and I can help with Swedish 🇸🇪

**Comment by lrynek** [comment]
I can help with Polish and Spanish also :)

**Comment by mchaov** [comment]
I can take Bulgarian

**Comment by froeder** [comment]
I can help PT-BR

**Comment by annacruz** [comment]
I could also help with pt-BR

**Comment by gabrielmanara** [comment]
I can help PT-BR :raised_hand_with_fingers_splayed:

**Comment by StudioPraktik** [comment]
We'd be happy to help with Hebrew!

**Comment by giuseongit** [comment]
(cc @SachaG)
Just to let anyone know: I'm current working on the internationalization of the platform [on my fork](https://github.com/giuseongit/StateOfJS/tree/i18n-support). Currently I've only worked on home, in the next 2/3 days I think I'll finish the surveys. If anyone is interested in helping I'll be very glad.

**Comment by sbaidon** [comment]
I can help with Spanish (Latam)

**Comment by ezhikov** [comment]
Hello. Can help with Russian.

**Comment by dulcelariz** [comment]
I can help with Spanish 👍

**Comment by awalin** [comment]
I can help with Bengali.
To be fair, coding itself is in English, so more than language, the important factor is understanding the local factors, like salary in USD does not make sense when we compare across countries, ay idea how we can show the salary data properly? Can we normalize it somehow?

**Comment by joeltankam** [comment]
I would love to help with French 🇫🇷

**Comment by oscarrodar** [comment]
I can help with Spanish and also to target developers in Costa Rica!

**Comment by justindra** [comment]
> I will help for Bahasa Indonesia 🇮🇩

Happy to help with Bahasa Indonesia too

**Comment by giuseongit** [comment]
I just read some code, the surveys are basically a bunch of `md` files and some english words scattered all over the codebase. While in `home` I set up a basic i18n support   #143 , I noticed that also the surveys have a basic support for languages. I need someone to help me write a more robust structure for handling different languages. Is there a more technical/detailed issue for this?

Also, some ui/ux help would be great, as I simply don't know where to put the language switch.

**Comment by prasadseth** [comment]
I can help with Hindi language

**Comment by FeherMarcell** [comment]
I can help with Hungarian :hungary:

**Comment by hamzaerbay** [comment]
I can help with Turkish 🤚

**Comment by kmelkon** [comment]
I can help with Arabic 🙇

**Comment by isader** [comment]
I can help with Arabic

**Comment by yknx4** [comment]
> I can help with Spanish 🖐️

I can help with Spanish too, especially Latin American Spanis (as it slightly differs from Peninsular Spanish)

**Comment by amir-s** [comment]
I can help with Farsi (Persian) ✋

**Comment by jhcastanod** [comment]
I can help with Spanish

**Comment by mgmgpyaesonewin** [comment]
I can help with Burmese(Myanmar) Language.

**Comment by maevadevs** [comment]
Malagasy here for Madagascar 🇲🇬

**Comment by ilgiznice** [comment]
I can help with Russian.

**Comment by mjx20045912** [comment]
I can help with Chinese (simplified)

**Comment by Tyrannogina** [comment]
> I can help with both Spanish (Spain) and Catalan (Spain)

Same here.

**Comment by adriantombu** [comment]
Here for the French translation if needed too 🥖 😊

**Comment by idododu** [comment]
> I can help with Chinese (simplified)

+1

**Comment by idododu** [comment]
> I can help with Chinese (simplified)

+1

**Comment by uxitten** [comment]
I can help Iran

**Comment by codeKameleon** [comment]
I can help with French :)

**Comment by maartenpeels** [comment]
I can help with translating to Dutch.

**Comment by handmadeGod** [comment]
Spanish here too!

**Comment by wilmersondasilva** [comment]
I can help with Brazilian Portuguese!

**Comment by nrifki** [comment]
I can help with French, Arabic and Chinese 😜

**Comment by uxitten** [comment]
@nrifki wooo 3 language

**Comment by IreneMarin** [comment]
> 
> 
> I can help with both Spanish (Spain) and Catalan (Spain)

Same here :)

**Comment by hakaari** [comment]
I can help with Georgian

**Comment by alex-ls** [comment]
Russian here happy to help

**Comment by mtancoigne** [comment]
> I can help with French. :-)

Me too

**Comment by waszqba** [comment]
along with @agatac and @sin I am also willing to translate to Polish :)

**Comment by EdPutans** [comment]
I can help translating to Russian and Lithuanian

**Comment by CalaoJuanPablo** [comment]
I can help with spanish

**Comment by tiomno** [comment]
Another Spanish speaker here ready to help!

**Comment by SachaG** [comment]
Just to give everybody a quick update: first of all, we're blown away by all the offers to help! It's the first time I'm this happy to see 99 comments on a GitHub issue ;)

So now we just need to figure out how this will work. We didn't really set up the site with i18n in mind so there's lots of things to adapt and @plouc is currently working on that. Once we have this working we'll also come up with some guidelines & workflow to let you know the best way to help us. 

Stay tuned!

**Comment by Fercas123** [comment]
I can help with Spanish (LatAm)

**Comment by ssong-eu** [comment]
> I can help with Korean 🇰🇷

can also help with Korean 🇰🇷

**Comment by nazzarkevich** [comment]
I can help with Ukranian 🇺🇦

**Comment by SimonSimCity** [comment]
German 🇩🇪  and Norwegian 🇳🇴  here 👋

**Comment by amanolar94** [comment]
Hello I could help with Greek :greece:

**Comment by yavorskiydima** [comment]
I can help with Russian

**Comment by Vilia13** [comment]
I can help with Russian =)

**Comment by mtancoigne** [comment]
i'm compiling all of this in a `{ "language": [ <people>] }` json file

**Comment by mtancoigne** [comment]
(I don't count the "emoji reactions", as I don't know if people are happy or willing to join

**Comment by mtancoigne** [comment]
Hey, I finished to copy paste (well, okay, I thought it would be quick) everything, and I now have a [JSON file with 36 locales in it](https://gist.github.com/mtancoigne/a2455973c471d1be9bf163b3f58e487c) and many people :)

@SachaG, this may help for later :)

I'll come here once a day for a week or two to complete the list.

**Comment by MohamadKh75** [comment]
> Hey, I finished to copy paste (well, okay, I thought it would be quick) everything, and I now have a [JSON file with 36 locales in it](https://gist.github.com/mtancoigne/a2455973c471d1be9bf163b3f58e487c) and many people :)
> 
> @SachaG, this may help for later :)
> 
> I'll come here once a day for a week or two to complete the list.

I was the first volunteer for Persian and you missed me 😐
BTW, Persian == Farsi == Irani

**Comment by SachaG** [comment]
@mtancoigne thanks for the help!

**Comment by tenCats** [comment]
Hello, I can help with Chinese🇨🇳 👋

**Comment by aghoneim92** [comment]
I would like to start with Arabic. Any pointers from where to begin?

**Comment by MaelWeb** [comment]
Well, maybe i can help with Chinese🇨🇳

**Comment by chendayang** [comment]
I can help with Chinese

**Comment by mtancoigne** [comment]
@MohamadKh75, sorry for that, its fixed now :)

**Comment by virgilbugnariu** [comment]
I can help with Romanian too

**Comment by Islam888** [comment]
I can help with Arabic.

**Comment by plouc** [comment]
@aghoneim92, thank you! there's an existing [PR](https://github.com/StateOfJS/StateOfJS/pull/144), but it's still in progress, it also contains documentation/guidance regarding translations.
I'll try to finish it this week-end.

**Comment by mukeshyadav** [comment]
I can try with either Sanskrit or Hindi language

**Comment by SimonSimCity** [comment]
I think it would be beneficial, since some languages have quite many supporters, to introduce a localization platform. https://www.transifex.com/ is one of my favourite, but there are much more who would give you access for free (I expect you to qualify as open-source project).

If this is too much integration, I suggest each team to organize the translation themselves. My first idea is that a first version could be set up using a google-document. Just paste the full file in which should be translated and maybe color the stuff which you've already translated. Maybe another color then if you are verifying the translations etc ... Everything after the initial PR for a language can then be fixed in additional PRs, opened by those who see it - but those then would need a confirmation by one known to the language I guess ... Or maybe I'm oversizing this 😅

@SachaG I'd specially like to hear your voice on this 😊

**Comment by wiktoriatomzik** [comment]
I can help with Polish.

**Comment by mtancoigne** [comment]
Hi ! The list was updated with newcomers :)

(@SimonSimCity I won't take part on reflexions about translating the 2018 survey, but I think there's something to think about for the next one (questions and results). A platform like Transifex may be something to think about)

**Comment by plouc** [comment]
@SimonSimCity, thank you for the suggestion, we might consider this kind of solution for the next survey, but for now we'll stick to plain yaml/markdown files.
Once my PR gets merged, we'll provide a guide, I'm not sure a google doc will do as copy/pasting at the end is error prone IMHO.

**Comment by TaqwaR** [comment]
I can help with Arabic.

**Comment by SimonSimCity** [comment]
@plouc The google docs was just an idea. My idea was as following:

1. Get together as a group per language.
1. Copy the YAML file into a document as you would do with plain text (I hope you all can read YAML)
1. Translate all phrases and color them e.g. yellow. All not marked are not yet translated.
1. Color yellow text in green if you verify that it is correct.
1. When the group agrees let one person of your team take the plain text from the doc, paste it back into the YAML files for your language and create the PR.

It's just an easy way to collaborate together as this list keeps growing 😉 I think you get the idea, so I won't keep this thread more busy than it already is.

**Comment by OsamaNabih** [comment]
I can help with Arabic.

**Comment by IsaacMiguel** [comment]
I can help with Spanish.

**Comment by Detachment** [comment]
I can help with Chinese (simplified).

**Comment by ysm0622** [comment]
[https://gitlocalize.com/](https://gitlocalize.com/)
![image](https://user-images.githubusercontent.com/18487241/48994339-06fdad00-f186-11e8-99da-95a191a780ab.png)

How about use this?
It looks nice

**Comment by SimonSimCity** [comment]
@plouc What do you mean..? YAML is listed here: https://docs.gitlocalize.com/file_formats.html

> We support `Ruby on Rails` i18n format and any framework or environment.

**Comment by plouc** [comment]
@SimonSimCity I mean regular YAML isn't supported, Rails specific format is:

> We support Ruby on Rails i18n format…

**Comment by deyan-a** [comment]
I can help with translating the survey to Bulgarian.

**Comment by tomstumshais** [comment]
I can help with Latvian.

**Comment by Filipzaleski** [comment]
Hey, I would love to help with polish :). Keep doing awesome job guys!

**Comment by pinkbunny1** [comment]
I can help with Korean :D

**Comment by pembeci** [comment]
Registering for Turkish.

**Comment by eko24ive** [comment]
I can also help with Ukranian 🇺🇦
Would like to team with @nazzarkevich

**Comment by olipeno** [comment]
I work at SurveyMonkey, you can use the multilingual surveys feature, all you need to do is upload translations in a .po format of your language choice and respondents will see a language dropdown while taking the survey.

**Comment by AmyLingJs** [comment]
I can help with Chinese

**Comment by TTtuntuntutu** [comment]
I can help with Chinese

**Comment by dadeef** [comment]
I can help with french and dutch

**Comment by Hesamp** [comment]
I can help with perisan / فارسی

**Comment by MrFatt** [comment]
Available for Chinese

**Comment by AndreiaFileno** [comment]
Already saw some people volunteering for PT-PT, but i can help with that as well if needed!

**Comment by idododu** [comment]
[CodePen: StateOfJs Localization Supporters](https://codepen.io/dododu/full/vQQOXY/)
generate a statistic chart from gist json file in order to see how many supporters for each language
![image](https://user-images.githubusercontent.com/7663884/49203025-a5d21580-f3e1-11e8-87c1-e946e8977091.png)

**Comment by michaellopez** [comment]
> [CodePen: StateOfJs Localization Supporters](https://codepen.io/dododu/full/vQQOXY/)
> generate a statistic chart from gist json file in order to see how many supporters for each language
> ![image](https://user-images.githubusercontent.com/7663884/49203025-a5d21580-f3e1-11e8-87c1-e946e8977091.png)

@idododu You should increase the height of the chart, otherwise some language labels are hidden and some people might not be aware of it and think the charts is incorrect. Good work 👍

**Comment by gustavofoa** [comment]
I also can help with pt-BR.

**Comment by mgomezg** [comment]
I can help with spanish

**Comment by vbelolapotkov** [comment]
I can help with russian

**Comment by mtancoigne** [comment]
(oh, BTW, it's been updated) @idododu Nice graph :) You may want to sort languages alphabetically, and update the source ;)

**Comment by pavilion2t** [comment]
I can help with Chinese (simplified).

**Comment by SachaG** [comment]
@olipeno that's pretty cool, we use Typeform currently but we should evaluate SurveyMonkey too. 

Also an update for everybody: this is the workflow we have in mind. Let's say Alice wants to translate the survey results to French. She would: 

1. Fork the StateOfJS repo to her own GitHub account.
2. Make an initial commit.
2. Open a new PR to this repo with a clear title, such as `[Translation] French`.

Note: in the PR description, Alice can paste an outline that we will provide that lists all the items that need to be translated.

Now if Alice didn't translate everything yet and Bob wants to help her translate to French, he would:

1. Search for any existing PRs for French and find Alice's PR.
2. Leave a comment on the PR asking for write access to Alice's fork.
3. Contribute his own commits to the same fork. 

Once Alice and Bob are happy with the result, Alice will then ask me (@SachaG) to review the PR, at which point I will merge it into `master`. 

This means that the first person to start a new translation PR will become the "manager" for that language and be responsible with adding collaborators and notifying us once all collaborators are happy with the result. 

Let us know what you think!

**Comment by SachaG** [comment]
P.S. please wait until we've merged the new `i18n` branch to master and published an official announcement to start though! We'll let you know soon :)

**Comment by mtancoigne** [comment]
@idododu, @SachaG, I created [a repo with the list](https://github.com/el-cms/soj-translators-enthusiasts) (for @idododu, so the chart can be updated automatically with jsDelivr or other). I won't update the gist anymore, but the repo :)

**Comment by MohamadKh75** [comment]
@SachaG what about RTL? Supported?

**Comment by SachaG** [comment]
@MohamadKh75 we'll start with "easy" languages like Spanish, German, etc. first, then move on to languages that might require special fonts (Russian, Chinese, etc.) and finally leave RTL languages for last since they will probably require the most work (unless of course we receive PRs to address RTL support).

**Comment by MohamadKh75** [comment]
> @MohamadKh75 we'll start with "easy" languages like Spanish, German, etc. first, then move on to languages that might require special fonts (Russian, Chinese, etc.) and finally leave RTL languages for last since they will probably require the most work (unless of course we receive PRs to address RTL support).

Or i can start to transliterate then whenever the RTL support is ready, we can simply change the strings...

**Comment by mtancoigne** [comment]
@idododu can you update with your chart with "https://cdn.jsdelivr.net/gh/el-cms/soj-translators-enthusiasts@master/list.json", i'd like to see if it's automatically updated when I update the JSON...

**Comment by uxitten** [comment]
We are involved with economic problems and our value money has dropped a lot.
Average salary in Iran is $5000 for a year now

<img width="904" alt="screen shot 2018-12-02 at 10 25 44 am" src="https://user-images.githubusercontent.com/1549069/49336711-a60a2500-f61c-11e8-940b-d0b3e2745c7a.png">

**Comment by reyesreg** [comment]
I can help with Filipino.

**Comment by idododu** [comment]
> @idododu can you update with your chart with "https://cdn.jsdelivr.net/gh/el-cms/soj-translators-enthusiasts@master/list.json", i'd like to see if it's automatically updated when I update the JSON...

chart updated

**Comment by 90lzy** [comment]
I can also help with Chinese (simplified)

**Comment by mtancoigne** [comment]
List updated (@idododu let's see if jsdeliver's cache updates in the next hours...)

**Comment by SachaG** [comment]
OK, I've published an announcement post along with clear instructions for everybody :) https://medium.com/@sachagreif/help-us-translate-the-state-of-javascript-2018-survey-results-1488efa525c1

I'll close this thread to avoid sending out 100+ notifications every time someone has a question, but don't hesitate to open new issue threads; or even better new PRs for each language :)

**Comment by ckwagaba** [comment]
Well, I bet you never heard of Luganda, but I'd like to help with that!

**Comment by isaaciverson** [comment]
I don't know how useful it'd be, but I'd love to help with an Esperanto translation!

**Comment by balazsorban44** [comment]
@isaaciverson and @ckwagaba I guess, it is not necessary to ask for permission anymore, you just follow the steps:

> OK, I've published an announcement post along with clear instructions for everybody :) https://medium.com/@sachagreif/help-us-translate-the-state-of-javascript-2018-survey-results-1488efa525c1
> 
> I'll close this thread to avoid sending out 100+ notifications every time someone has a question, but don't hesitate to open new issue threads; or even better new PRs for each language :)

@SachaG, maybe put a link to the Medium article in its own section in the README file, so people can immediatelly see how to contribute?

**Comment by ivanfretes** [comment]
I can help with Spanish

**Comment by SachaG** [comment]
I've made some small edits to the content: https://github.com/StateOfJS/StateOfJS/commit/39701f38484fa35c23bae3df48fb9deb45ed1204

**Comment by balazsorban44** [comment]
@SachaG can we just update our fork like described here?
https://gist.github.com/CristinaSolana/1885435

**Comment by SachaG** [comment]
Yeah I think so?
