### ISSUE TITLE
Tool ranking is wrong on section tools overview chart

### ISSUE THREAD

**Issue by plouc** [StateOfJS/StateOfJS#88]
<img width="640" alt="capture d ecran 2018-11-03 a 19 41 47" src="https://user-images.githubusercontent.com/501642/47951193-9dccb480-dfa0-11e8-9551-ec05f2fa4020.png">

**Comment by SachaG** [comment]
Tanking?

**Comment by plouc** [comment]
ranking :)

**Comment by plouc** [comment]
The problem still exists

**Comment by SachaG** [comment]
Oh? where do you see it?

**Comment by SachaG** [comment]
Oh right that `ranking.yml` file gets regenerated automatically right? If you stop it from being overwritten I can fix it manually?

**Comment by plouc** [comment]
Thank you for the proposal, it's now fixed (https://github.com/StateOfJS/StateOfJS/commit/0234749280bff1eecd1b32eececae8fa440843d0)
