### ISSUE TITLE
Affinity: Chord Diagram/Heatmap

### ISSUE THREAD

**Issue by plouc** [StateOfJS/StateOfJS#9]
Create configurable Chord chard that lets you pick which sections to compare. Put it in its own section.

Alternatively, use heatmap like 2016 results.

**Comment by plouc** [comment]
First we need to make the required data available. (@plouc)

**Comment by plouc** [comment]
Available at https://philatist-albert-72527.netlify.com/2017/connections/

**Comment by SachaG** [comment]
We should think about the colors, it doesn't really make sense to use the same color scale here?

**Comment by SachaG** [comment]
Unless we base the scale on the size of each section somehow?

**Comment by plouc** [comment]
I close this issue as you added colors for each section.
