### ISSUE TITLE
Tooltips appear behind chart

### ISSUE THREAD

**Issue by SachaG** [StateOfJS/StateOfJS#90]
Because of the order they appear in the DOM. The solution would be moving the ticks to be rendered after the chart.

![https://d3vv6lp55qjaqc.cloudfront.net/items/3o1B2T3X1d430v470D44/Screen%20Shot%202018-11-03%20at%2021.10.56.png?X-CloudApp-Visitor-Id=43642&v=26ffaacd](https://d3vv6lp55qjaqc.cloudfront.net/items/3o1B2T3X1d430v470D44/Screen%20Shot%202018-11-03%20at%2021.10.56.png?X-CloudApp-Visitor-Id=43642&v=26ffaacd)

**Comment by SachaG** [comment]
There is also the issue that the hover zone doesn't extend far enough: https://stackoverflow.com/questions/53274575/extending-an-svg-tooltips-hover-zone-out-of-its-parent-elements-bounds

**Comment by plouc** [comment]
Fixed, please make sure to re-install deps as it involves nivo packages upgrade.
