### ISSUE TITLE
Start button and logo

### ISSUE THREAD

**Issue by plouc** [StateOfJS/StateOfJS#97]
Maybe we should put the start button above|below the logo, or put it on top with the same grey background as the one used for the website

<img width="581" alt="screenshot 2018-11-11 at 18 35 58" src="https://user-images.githubusercontent.com/501642/48311304-1525c800-e5e1-11e8-9cf2-908eb120db33.png">

**Comment by SachaG** [comment]
I kinda like the effect… but yes I did think about putting the button below the logo, I'll try it.
